version: '2'

services:
  logservice:
    build:
      context: ./logservice/
      dockerfile: Dockerfile
    environment:
      - "MONGODB_CONNSTRING=mongodb://velomeister:velomeister@mongo:27017"

  roundrobin:
    build:
      context: ./roundrobin/
      dockerfile: Dockerfile
    ports:
      - "80:6000"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=velomeister"
      - "MONGO_INITDB_ROOT_PASSWORD=velomeister"
      - "MONGO_INITDB_DATABASE=database"
      - "MONGO_INITDB_COLLECTION=messages"