version: '2'

services:
  logservice:
    build:
      context: ./logservice/
      dockerfile: Dockerfile
    container_name: logservice
    ports:
      - "35001-35003:6000"
    environment:
      - "MONGODB_CONNSTRING=mongodb://velomeister:velomeister@mongo:27017"

  roundrobin:
    build:
      context: ./roundrobin/
      dockerfile: Dockerfile
    container_name: roundrobin
    ports:
      - "35000:6000"

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "80:6000"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=velomeister"
      - "MONGO_INITDB_ROOT_PASSWORD=velomeister"
      - "MONGO_INITDB_DATABASE=database"